services:
  odoo:
    image: odoo:18.0
    container_name: odoo18
    ports:
      - '8069:8069'
    env_file:
      - .env
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/opt/odoo/modules
      - ./config:/etc/odoo
    restart: unless-stopped
    command: odoo --config=/etc/odoo/odoo.conf

volumes:
  odoo-web-data:
